<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
	
function getSitemapLinks() {
    $site_map_list = array('Home' => '',
        'Build Your Onw Ring' => 'engagement/search',
        'Build Your Onw Earrings' => 'jewelry/build_earings',
        'Build Your Own Diamond Pendant' => 'jewelry/buildiamond_pendant',
        'Build Your Own Three-Stone Ring' => 'jewelry/buildthree_stonesring',
        'Cushion Solitare' => 'testengagementrings/engagement_ring_listings/103',
        'Emerald Solitare' => 'testengagementrings/engagement_ring_listings/101',
        'Heart Solitare' => 'testengagementrings/engagement_ring_listings/54',
        'Interchange Heads' => 'testengagementrings/engagement_ring_listings/53',
        'Marquise Solitare' => 'testengagementrings/engagement_ring_listings/98',
        'Oval Solitare' => 'testengagementrings/engagement_ring_listings/100',
        'Pear Solitare' => 'testengagementrings/engagement_ring_listings/99',
        'Princess Solitare' => 'testengagementrings/engagement_ring_listings/102',
        'Round Solitare' => 'testengagementrings/engagement_ring_listings/97',
        'Trillion Solitare' => 'testengagementrings/engagement_ring_listings/55',
        'Collections' => 'qualitygoldrings/qualitycate/4',
        'Watches' => 'qualitygoldrings/qualitycate/1',
        'Tripple X' => 'diamonds/search/true/SG',
        'Hearts and Arrows' => 'diamonds/search/true/B',
        'Round' => 'diamonds/search/true/B',
        'Cushion' => 'diamonds/search/true/C',
        'Oval' => 'diamonds/search/true/O',
        'Pear' => 'diamonds/search/true/P',
        'Princess' => 'diamonds/search/true/PR',
        'Radiant' => 'diamonds/search/true/R',
        'Emerald' => 'diamonds/search/true/E',
        'Asscher' => 'diamonds/search/true/AS',
        'Marquise' => 'diamonds/search/true/M',
        'Heart' => 'diamonds/search/true/H',
        'Contact Us' => 'site/page/contactus',
        'Diamond & Jewelry Purchase Program' => 'site/page/purchase-program',
        'Jewelry Guarantee' => 'site/page/jewelry-guarantee',
        'Lifetime Upgrade' => 'site/page/diamond-upgrade',
        'Customer Satisfaction' => 'site/page/customer-satisfaction',
        '14K &amp; 10K Fancy Watches' => 'qualitygoldrings/qualitycate/5',
        'Braun' => 'qualitygoldrings/qualitycate/7',
        'Buren 1873' => 'qualitygoldrings/qualitycate/8',
        'Cardinal' => 'qualitygoldrings/qualitycate/9',
        'Charles-Hubert Paris' => 'qualitygoldrings/qualitycate/10',
        'Chisel' => 'qualitygoldrings/qualitycate/12',
        'Citadel' => 'qualitygoldrings/qualitycate/13',
        'Collegiate' => 'qualitygoldrings/qualitycate/14',
        'Disney' => 'qualitygoldrings/qualitycate/62',
        'Ed Hardy' => 'qualitygoldrings/qualitycate/84',
        'Garfield' => 'qualitygoldrings/qualitycate/85',
        'Hello Kitty' => 'qualitygoldrings/qualitycate/86',
        'Ingersoll' => 'qualitygoldrings/qualitycate/87',
        'Invicta' => 'qualitygoldrings/qualitycate/89',
        'Jacqueline Kennedy' => 'qualitygoldrings/qualitycate/90',
        'Jacques du Manoir' => 'qualitygoldrings/qualitycate/91',
        'Kremena' => 'qualitygoldrings/qualitycate/92',
        'Le Petit Prince' => 'qualitygoldrings/qualitycate/93',
        'Marvel' => 'qualitygoldrings/qualitycate/95',
        'MLB' => 'qualitygoldrings/qualitycate/101',
        'Moog Paris' => 'qualitygoldrings/qualitycate/132',
        'Mountroyal' => 'qualitygoldrings/qualitycate/136',
        'NBA' => 'qualitygoldrings/qualitycate/138',
        'NFL' => 'qualitygoldrings/qualitycate/169',
        'NHL' => 'qualitygoldrings/qualitycate/202',
        'Penguin' => 'qualitygoldrings/qualitycate/234',
        'Red balloon' => 'qualitygoldrings/qualitycate/235',
        'S.W.I.55 Navy' => 'qualitygoldrings/qualitycate/236',
        'Simon Chang' => 'qualitygoldrings/qualitycate/237',
        'Steinhausen' => 'qualitygoldrings/qualitycate/238',
        'Swiss Eagle' => 'qualitygoldrings/qualitycate/239',
        'Thomas &amp; Friends' => 'qualitygoldrings/qualitycate/241',
        'Time Teachers' => 'qualitygoldrings/qualitycate/242',
        'Tween Collection' => 'qualitygoldrings/qualitycate/268',
        'U.S. Military' => 'qualitygoldrings/qualitycate/272',
        'Vivienne Westwood' => 'qualitygoldrings/qualitycate/273',
        'Wrist Armor' => 'qualitygoldrings/qualitycate/274',
        'Personalized' => 'davidsternrings/personalized',
        'Akoya Pearls' => 'stullerygoldrings/stuller_ring_listings/?cate=akoya_pearls',
        'Bangles' => 'stullerygoldrings/stuller_ring_listings/?cate=bangles',
        'Bfly Items' => 'stullerygoldrings/stuller_ring_listings/?cate=bfly_items',
        'Diamond Earrings' => 'stullerygoldrings/stuller_ring_listings/?cate=diamond_earrings',
        'Freshwater Pearls' => 'stullerygoldrings/stuller_ring_listings/?cate=freshwater_pearls',
        'Gemstone Earrings' => 'stullerygoldrings/stuller_ring_listings/?cate=gemstone_earrings',
        'Hersey Kisses' => 'stullerygoldrings/stuller_ring_listings/?cate=hersey_kisses',
        'Diamond Wedding Bands' => 'stuller_new_rings/wedding_bands_diamond',
        'Ladies Wedding Bands' => 'stuller_new_rings/wedding_bands_ladies',
        'Wedding Bands' => 'stuller_new_rings/wedding_bands_platinum',
        'Men\'s Wedding Bands' => 'stuller_new_rings/wedding_bands_mens',
        'Diamond Stud Earrings' => 'stuller_new_rings/diamond_stud_earrings',
        'Diamond Hoops' => 'stuller_new_rings/diamond_hoop_earings',
        'Gemstone Earrings' => 'stuller_new_rings/gemstone_earings',
        'Diamond Bracelets' => 'braceletsection/bracelet_listings',
        'Rolex Quality Gold' => 'rolexrings/rolex_rings_listing',
        'New Products' => 'stullerygoldrings/stuller_ring_listings/?cate=new_products',
        'Pendants' => 'stullerygoldrings/stuller_ring_listings/?cate=pendants',
        'Vintage and Floral' => 'stullerygoldrings/stuller_ring_listings/?cate=vintage_and_floral',
        'Watches' => 'stullerygoldrings/stuller_ring_listings/?cate=watches',
        '1928' => 'qualitygoldrings/qualitycate/279',
        'Amore La Vita' => 'qualitygoldrings/qualitycate/389',
        'Brilliant Embers' => 'qualitygoldrings/qualitycate/606',
        'Cheryl M' => 'qualitygoldrings/qualitycate/733',
        'Chisel' => 'qualitygoldrings/qualitycate/849',
        'Diamond Fascination' => 'qualitygoldrings/qualitycate/1240',
        'Diego Massimo' => 'qualitygoldrings/qualitycate/1280',
        'Edward Mirell' => 'qualitygoldrings/qualitycate/1302',
        'Emma Grace' => 'qualitygoldrings/qualitycate/1382',
        'Just Like Mommy' => 'qualitygoldrings/qualitycate/1396',
        'Kelly Waters' => 'qualitygoldrings/qualitycate/1411',
        'Leslie\'s' => 'qualitygoldrings/qualitycate/1529',
        'Majestik' => 'qualitygoldrings/qualitycate/1530',
        'Moissanite' => 'qualitygoldrings/qualitycate/1554',
        'Nightfall' => 'qualitygoldrings/qualitycate/1598',
        'Nikki Lissoni' => 'qualitygoldrings/qualitycate/1630',
        'Reflection Beads' => 'qualitygoldrings/qualitycate/1675',
        'Sentimental Expressions' => 'qualitygoldrings/qualitycate/1834',
        'Shey Couture' => 'qualitygoldrings/qualitycate/1912',
        'Silver Notes' => 'qualitygoldrings/qualitycate/2008',
        'Spirit by Chelsea Taylor' => 'qualitygoldrings/qualitycate/2053',
        'Stackable Expressions' => 'qualitygoldrings/qualitycate/2067',
        'Sterling Shimmer' => 'qualitygoldrings/qualitycate/2173',
        'Tattooed Steel' => 'qualitygoldrings/qualitycate/2199',
        'Vatican' => 'qualitygoldrings/qualitycate/2218',
        'White Ice' => 'qualitygoldrings/qualitycate/2244',
        'White Night Diamonds' => 'qualitygoldrings/qualitycate/2305',
        'Custom Design' => 'engagement/engagement_rings',
        'Education and Guidance' => 'site/page/education-guidance',
        'Custom Inscriptions' => 'site/page/custom-inscriptions',
        'Privacy Policy' => 'site/page/privacypolicy',
        'APO/FPO' => 'site/page/apo_fpo',
        'SHIPPING TO HAWAII OR ALASKA?' => 'site/page/shipping_tohawi',
        'Terms and Conditions' => 'site/page/terms_conditions',
        'Jewelry Guarantee' => 'site/page/jewelry-guarantee',
        'Lifetime Upgrade' => 'site/page/diamond-upgrade',
        'Quality and Expertise' => 'site/page/quality_experties',
        'Testimonials' => 'site/page/testimonials',
        'Shipping Cost & Times' => 'site/page/shipping-cost',
        'Track Your Order' => 'site/page/track-order',
        'Returns' => 'site/page/returnpolicies',
        'Repairs' => 'site/page/repairs',
        'Safe & secure Shopping' => 'site/page/secure-shopping',
        'Diamond Carat' => 'site/page/diamond-carat',
        'Diamond Color' => 'site/page/diamond-color',
        'Diamond Clarity' => 'site/page/diamond-clarity',
        'Diamond Shapes' => 'site/page/diamond-shapes',
        'Cut Performance' => 'site/page/cut-performance',
        'Hearts and Arrows Page' => 'site/page/hearts-arrows',
        'Visible Perfection' => 'site/page/visible-perfection',
        'Our History' => 'site/page/our_history',
        'Diamonds' => 'site/page/diamonds'
    );
    
    return $site_map_list;
}